{
 "title": "Horizon",
 "tags": [ "laravel" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Horizon: Recent Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "horizon_recent_jobs", "legendFormat": "Recent Jobs" }
   ]
  },
  {
   "title": "Horizon: Failed Jobs Per Hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "horizon_failed_jobs_per_hour", "legendFormat": "Failed Jobs Per Hour" }
   ]
  },
  {
   "title": "Horizon: Current Workload",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "horizon_current_workload", "legendFormat": "Workload" }
   ]
  },
  {
   "title": "Horizon: Processes Per Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "horizon_processes_per_queue{queue!=\"\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Horizon: Jobs Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "horizon_jobs_per_minute", "legendFormat": "Jobs Per Minute" }
   ]
  },
  {
   "title": "Horizon Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "horizon_status" }
   ]
  },
  {
   "title": "User Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "user_count" }
   ]
  },
  {
   "title": "Lot Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lot_count" }
   ]
  },
  {
   "title": "Auction Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "auction_count" }
   ]
  },
  {
   "title": "Bid Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bid_count" }
   ]
  },
  {
   "title": "Horizon Master Supervisors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "horizon_master_supervisors" }
   ]
  }
 ]
}