{
 "title": "Laravel & Horizon",
 "tags": [ "laravel" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Horizon: Jobs Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "app_horizon_jobs_per_minute", "legendFormat": "Jobs Per Minute" }
   ]
  },
  {
   "title": "Horizon Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_horizon_status" }
   ]
  },
  {
   "title": "User Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_user_count" }
   ]
  }
 ]
}